core/urls.py
from . import views
from django.urls import path

app_name = "core"

urlpatterns = [
    path("movie/<int:movie_id>/image/upload/", views.MovieImageUploadView.as_view(), name="image"),
    path("movie/<int:movie_id>/vote/<int:pk>/", views.UpdateVote.as_view(), name="update_vote"),
    path("movie/<int:movie_id>/vote", views.CreateVote.as_view(), name="create_vote"),
    path("person/<int:pk>/", views.PersonDetailView.as_view(), name="person"),
    path("movie/<int:pk>/", views.MovieDetailView.as_view(), name="detail"),
    path("movies/", views.MovieListView.as_view(), name="list"),
    path("top_movies/", views.TopMovieView.as_view(), name="top_movies")
]

mymdb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls", namespace="user")),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_view

app_name = "user"

urlpatterns = [
    path("login/", auth_view.LoginView.as_view(template_name="user/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum

from uuid import uuid4


class PersonManager(models.Manager):

    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            "directed",
            "writing_credits",
            "role_set__movie",
        )


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    born = models.DateField(blank=True, null=True)
    died = models.DateField(blank=True, null=True)

    objects = PersonManager()

    class Meta:
        ordering = "first_name", "last_name",

    def __str__(self):
        return self.first_name + " " + self.last_name


class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            "director"
        )
        qs = qs.prefetch_related("writers", "actors")

        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum("vote__value"))

        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum("vote__value"))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by("-vote_sum")
        qs = qs[:limit]

        return qs


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, "NR - Not Rated"),
        (RATED_G, "G - General Audience"),
        (RATED_PG, "PG - Parental Guidance"),
        (RATED_R, "R - Restricted"),
    )

    title = models.CharField(max_length=155)
    plot = models.TextField()
    year = models.PositiveSmallIntegerField()
    rating = models.PositiveSmallIntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveSmallIntegerField()
    website = models.URLField(blank=True)

    director = models.ForeignKey(
        Person,
        on_delete=models.SET_NULL,
        related_name="directed",
        null=True,
        blank=True,
    )
    writers = models.ManyToManyField(
        Person,
        related_name="writing_credits",
        blank=True
    )
    actors = models.ManyToManyField(
        to=Person,
        through="Role",
        related_name="acting_credits",
        blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = "-year", "title",

    def __str__(self):
        return self.title


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=60)

    class Meta:
        unique_together = "movie", "person", "name",

    def __str__(self):
        return self.name


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return self.model.objects.get(
                movie=movie, user=user
            )
        except Vote.DoesNotExist:
            return self.model(
                movie=movie,
                user=user,
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "😄"),
        (DOWN, "☹"),
    )
    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    objects = VoteManager()

    class Meta:
        unique_together = "user", "movie",


def movie_directory_path_with_uuid(instance, filename):

    return "{}/{}".format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.movie.title

core/forms.py
from .models import Vote, MovieImage
from django import forms


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = "__all__"
        labels = {None}

    def __init__(self, **kwargs):
        super(VoteForm, self).__init__(**kwargs)

        self.fields["user"].widget = forms.HiddenInput()
        self.fields["user"].disabled = True

        self.fields["movie"].widget = forms.HiddenInput()
        self.fields["movie"].disabled = True

        self.fields["value"].label = "Vote"
        self.fields["value"].widget = forms.RadioSelect()
        self.fields["value"].choices = Vote.VALUE_CHOICES


class MovieImageForm(forms.ModelForm):

    class Meta:
        model = MovieImage
        fields = "__all__"
        widgets = {"movie": forms.HiddenInput(),
                   "user": forms.HiddenInput()}

    def __init__(self, **kwargs):
        super(MovieImageForm, self).__init__(**kwargs)
        self.fields["user"].disabled = True
        self.fields["movie"].disabled = True

core/views.py
from . import models, forms, mixins

import django
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin


class MovieListView(mixins.CachePageVaryOnCookieMixin, generic.ListView):
    model = models.Movie
    paginate_by = 12


class MovieDetailView(generic.DetailView):
    queryset = models.Movie.objects.all_with_related_persons_and_score()

    def get_context_data(self, **kwargs):
        ctx = super(MovieDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            ctx["image_form"] = forms.MovieImageForm()

            vote = models.Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user,
            )

            if vote.id:
                vote_form_url = reverse("core:update_vote", kwargs={
                    "movie_id": vote.movie.id,
                    "pk": vote.id
                })
            else:
                vote_form_url = reverse("core:create_vote", kwargs={
                    "movie_id": self.object.id
                })

            vote_form = forms.VoteForm(instance=vote)
            ctx["vote_form"] = vote_form
            ctx["vote_form_url"] = vote_form_url

        return ctx


class PersonDetailView(generic.DetailView):
    queryset = models.Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, generic.CreateView):
    form_class = forms.VoteForm

    def get_initial(self):
        initial = super(CreateVote, self).get_initial()
        initial["user"] = self.request.user.id
        initial["movie"] = self.kwargs["movie_id"]

        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse("core:detail", args=[movie_id])

    def render_to_response(self, context, **response_kwargs):
        movie_id = context["object"].id
        movie_detail_url = reverse("core:detail", args=[movie_id])

        return redirect(movie_detail_url)


class UpdateVote(LoginRequiredMixin, generic.UpdateView):
    form_class = forms.VoteForm
    queryset = models.Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super(UpdateVote, self).get_object(queryset=queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied("Can't change another user's vote")
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse("core:detail", args=[movie_id])

    def render_to_response(self, context, **response_kwargs):
        movie_id = context["object"].id
        movie_detail_url = reverse("core:detail", args=[movie_id])
        return redirect(movie_detail_url)


class MovieImageUploadView(LoginRequiredMixin, generic.CreateView):
    form_class = forms.MovieImageForm

    def get_initial(self):
        initial = super(MovieImageUploadView, self).get_initial()
        initial["user"] = self.request.user.id
        initial["movie"] = self.kwargs.get("movie_id")

        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs.get("movie_id")
        movie_detail_url = reverse('core:detail', args=[movie_id])

        return movie_detail_url

    def get_success_url(self):
        movie_id = self.kwargs.get("movie_id")
        movie_detail_url = reverse("core:detail", args=[movie_id])

        return movie_detail_url


class TopMovieView(generic.ListView):
    template_name = "core/top_movies_list.html"

    def get_queryset(self):
        limit = 10
        key = "top_movies_%s" % limit
        cached_qs = cache.get(key)

        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()

            if same_django:
                return cached_qs

        qs = models.Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)

        return qs

templates/core/movie_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ object.title }} - {{ block.super }}{% endblock title %}

{% block main %}
  <div class="col">
    <h1>{{ object.title }} - {{ object.year }}</h1>
    <p class="lead">
      {{ object.plot }}
    </p>
  </div>

  <ul class="movie-image list-inline">
    {% for movie in object.movieimage_set.all %}
      <li class="list-inline-item">
        <img width="100%" src="{{ movie.image.url }}">
      </li><br><br>
    {% endfor %}
  </ul>
{% endblock main %}

{% block sidebar %}
  <div>
    <span class="font-weight-bold text-muted">This movie is rated:</span>
    <span class="badge badge-primary">
      {{ object.get_rating_display }}
    </span>
  </div><br>
  <div>
    <span class="font-weight-bold text-muted">Score: </span> {{ object.score|default_if_none:"TBD" }}
  </div>

  <div>
    <span class="font-weight-bold text-muted">Director: </span>
    {% if object.director %}
      <a href="{% url 'core:person' object.director.pk %}">{{ object.director }}</a> <br>
    {% endif %}

    <span class="font-weight-bold text-muted">Writers: </span>
    <ul style="list-style: none; margin-left: -20px">
      {% for writer in object.writers.all %}
        <li><a href="{% url 'core:person' writer.pk %}">
          {{ writer.first_name }} {{ writer.last_name }}</a>
        </li>
      {% endfor %}
    </ul>

    <span class="font-weight-bold text-muted">Cast: </span>
    <ul style="list-style: none; margin-left: -20px;">
      {% for actor in object.actors.all %}
        <li>
          <a href="{% url 'core:person' actor.pk %}">{{ actor.first_name }} {{ actor.last_name }}</a>
        </li>
      {% endfor %}
    </ul>

    <span class="font-weight-bold text-muted">Runtime: </span> {{ object.runtime }}
  </div>

  <div>
  <style>
    label[for="id_value_0"], label[for="id_image"] {
      display: none;
    }

    form {
      margin-left: 20px;
    }
  </style>
  <br>
    <p class="font-weight-bold text-muted mb-2">Vote:</p>
    {% if vote_form %}
      <form method="post" action="{{ vote_form_url }}">
        {% csrf_token %}
        {{ vote_form|crispy }}
        <button class="btn btn-primary" type="submit">Vote</button>
      </form>
    {% else %}
      <p><a href="{% url 'user:login' %}?next={{request.path}}">Login</a> to vote for this</p>
    {% endif %}
  </div><br>

  <div>
    <span class="font-weight-bold text-muted">Upload new image: </span>
    {% if image_form %}
      <form method="post"
          enctype="multipart/form-data"
          action="{% url 'core:image' object.id %}">
        {% csrf_token %}
        {{ image_form|crispy }}
        <button class="btn btn-primary" type="submit">Upload</button>
      </form>
    {% else %}
      <br><a href="{% url 'user:login' %}?next={{request.path}}">Login</a> to upload images.
    {% endif %}
  </div>
{% endblock sidebar %}

templates/core/movie_list.html
{% extends "base.html" %}
{% block title %}Movie List{% endblock title %}
{% block main %}
  <ul>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:detail' movie.pk %}">{{ movie }}</a>
      </li>
    {% empty %}
      No movies yet.
    {% endfor %}
  </ul>

  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        <li class="page-item">
          <a href="{% url 'core:list' %}?page=1" class="page-link">First</a>
        </li>

        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="{% url 'core:list' %}?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.previous_page_number }}</a>
          </li>
        {% endif %}

        <li class="page-item active">
          <a href="{% url 'core:list' %}?page={{ page_obj.number }}" class="page-link">{{ page_obj.number }}</a>
        </li>

        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="{% url 'core:list' %}?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.next_page_number }}</a>
          </li>
        {% endif %}

        <li class="page-item">
          <a href="{% url 'core:list' %}?page=last" class="page-link">Last</a>
        </li>
      </ul>
    </nav>
  {% endif %}
{% endblock main %}

templates/core/person_detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.first_name }} {{ object.last_name }}
{% endblock title %}

{% block main %}
  <h1>{{ object }}</h1>
  {% if object.role_set.all %}
    <h2>Actor</h2>
    <ul>
      {% for role in object.role_set.all %}
        <li>
          <a href="{% url 'core:detail' role.movie.pk %}">{{ role.movie }}</a> : {{ role.name }}
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if object.writing_credits.all %}
    <h2>Writer</h2>
    <ul>
      {% for movie in object.writing_credits.all %}
        <li>
          <a href="{% url 'core:detail' movie.pk %}">{{ movie.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  {% if object.directed.all %}
    <h2>Director</h2>
    <ul>
    {% for movie in object.directed.all %}
      <li>
        <a href="{% url 'core:detail' movie.pk %}">{{ movie.title }}</a>
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock main %}

templates/core/top_movies_list.html
{% extends "base.html" %}
{% load cache %}

{% block title %}Top 10 Movies{% endblock title %}

{% block main %}
  <h1>Top 10 Movies</h1>
  <ol>
    {% for movie in object_list %}
      <li>
        <a href="{% url 'core:detail' movie.id %}">{{ movie.title }}</a>
      </li>
    {% endfor %}
  </ol>
{% endblock main %}