core/urls.py
from . import views
from django.urls import path

app_name = "core"

urlpatterns = [
    path("movie/<int:movie_id>/image/upload/", views.MovieImageUploadView.as_view(), name="image"),
    path("movie/<int:movie_id>/vote/<int:pk>/", views.UpdateVote.as_view(), name="update_vote"),
    path("movie/<int:movie_id>/vote", views.CreateVote.as_view(), name="create_vote"),
    path("person/<int:pk>/", views.PersonDetailView.as_view(), name="person"),
    path("movie/<int:pk>/", views.MovieDetailView.as_view(), name="detail"),
    path("movies/", views.MovieListView.as_view(), name="list"),
    path("top_movies/", views.TopMovieView.as_view(), name="top_movies")
]

mymdb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls", namespace="user")),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_view

app_name = "user"

urlpatterns = [
    path("login/", auth_view.LoginView.as_view(template_name="user/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>
    {% block title %}MyMDB{% endblock title %}
  </title>
  <style>
    .mymdb-masthead {
      background-color: #eee;
      margin-bottom: 1em;
    }
  </style>
</head>
<body>
  <div class="mymdb-masthead">
    <div class="container">
      <nav class="nav">
        <div class="navbar-brand">MyMDB</div>
        <a class="nav-link" href="{% url 'core:list' %}">Movies</a>
        <a class="nav-link" href="{% url 'core:top_movies' %}">Top 10 Movies</a>
        {% if request.user.is_authenticated %}
          <a class="nav-link ml-auto" href="{% url 'user:logout' %}">Logout</a>
        {% else %}
          <ul class="nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Register</a>
            </li>
          </ul>
        {% endif %}
      </nav>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-8 mymdb-main">
        {% block main %}{% endblock main %}
      </div>

      <div class="col-sm-3 offset-sm-1 mymdb-sidebar" >
        {% block sidebar %}{% endblock sidebar %}
      </div>
    </div>
  </div>
</body>
</html>